--Criando tabela usuario, com auto encremento.

CREATE TABLE GLO_USUARIO (
    USU_IN_CODIGO NUMBER PRIMARY KEY NOT NULL,
    PER_IN_CODIGO NUMBER,
    USU_ST_LOGIN VARCHAR2(100),
    USU_ST_NOME VARCHAR2(100),
    USU_ST_EMAIL VARCHAR2(100),
    USU_ST_SENHA VARCHAR2(100),
    USU_ST_TIPO VARCHAR2(100),
    USU_TELEFONE VARCHAR2(100),
    DATA_NASCIMENTO DATE,
    DATA_INCLUSAO DATE,
    DATA_EXCLUSAO DATE,
    ENDERECO VARCHAR2(100)
    USU_STATUS VARCHAR2(20)
);

---
CREATE SEQUENCE GLO_USUARIO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

----
CREATE OR REPLACE TRIGGER USUARIO_BIR
BEFORE INSERT ON GLO_USUARIO
FOR EACH ROW
BEGIN
    SELECT GLO_USUARIO_SEQ.NEXTVAL INTO :NEW.USU_IN_CODIGO FROM DUAL;
END;


------------------------------------------------------
--Function para tela de login

CREATE OR REPLACE FUNCTION AUTENTICA_USUARIO_FUNC (P_USERNAME IN VARCHAR2, P_PASSWORD IN VARCHAR2)
RETURN BOOLEAN
AS
MVAL NUMBER := 0;
BEGIN
SELECT 1 INTO MVAL FROM GLO_USUARIO A
WHERE UPPER(A.USU_ST_LOGIN) = UPPER(P_USERNAME)
AND A.PASSWORD = P_PASSWORD
AND A.USU_STATUS = 'Ativo';
RETURN (TRUE);
EXCEPTION
WHEN NO_DATA_FOUND THEN
RETURN FALSE;
END;

-------------------------------------
--Conceder cota na table space para usuario

ALTER USER NOME_DO_USUÁRIO QUOTA 100M ON USERS;