SELECT * FROM INTRA_AVISOS_LEITURA WHERE AVI_IN_CODIGO = 2037

DELETE FROM INTRA_AVISOS_LEITURA WHERE AVIL_IN_CODIGO = 251596

SELECT * FROM INTRA_AVISOS WHERE AVI_ST_TITULO LIKE '%COLEGA%' AND AVI_DT_INCLUSAO = to_char('07/10/2024')